config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'my-dragons', to: 'pages#my_dragons'
  get 'my-bookings', to: 'pages#my_bookings'

  resources :dragons do
    resources :bookings, only: :create
  end
  resources :bookings, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  attr_reader :total_price
  belongs_to :user
  belongs_to :dragon

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start_date

  include PgSearch::Model

  pg_search_scope :search_by_dragon_name,
    associated_against: {
      dragon: [:name, :category]
       },
    using: {
      tsearch: { prefix: true }
    }

  def total_price
    days = (self.end_date - self.start_date).to_i
    total_price = self.dragon.price_per_day * days
  end

  def countdown
    date = Date.today
    days_left = (self.start_date - date).to_i
  end

  def days_remaining
    days_left = (self.end_date - self.start_date).to_i
  end

  def start_time
    self.start_date
  end

  def end_time
    self.end_date
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/dragon.rb
class Dragon < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  geocoded_by :address

  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, presence: true
  validates :category, presence: true
  validates :age, presence: true
  validates :price_per_day, presence: true

  include PgSearch::Model

  pg_search_scope :search_by_name_and_category,
    against: [ :name, :category, :age, :address],
    associated_against: {
      user: [ :first_name, :last_name ]
       },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :fetch_dragon, only: %i[create]

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.dragon = @dragon
    @booking.user = current_user

    rented = false
    bookings_for_dragon = Booking.where(dragon_id: @booking.dragon_id)

    bookings_for_dragon.each do |booking|
      starting_date = booking.start_date
      ending_date = booking.end_date
      if @booking.start_date.between?(starting_date, ending_date) || @booking.end_date.between?(starting_date, ending_date)
        rented = true
      end
    end

    if rented
      redirect_to dragon_path(@booking.dragon_id), alert: "This Dragon is already booked in the period you want to book it :("
    else
      if @booking.save
        redirect_to my_bookings_path
      else
        render 'dragons/show'
      end
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to my_bookings_path
  end

  private

  def fetch_dragon
    @dragon = Dragon.find(params[:dragon_id])
    authorize @dragon
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end


end

app/controllers/dragons_controller.rb
class DragonsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :fetch_dragon, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      # sql_query = "name @@ :query OR category @@ :query"
      # @dragons = policy_scope(Dragon).geocoded.where(sql_query, query: "%#{params[:query]}%")
      # raise
      @dragons = policy_scope(Dragon).geocoded.search_by_name_and_category(params[:query])
    else
      @dragons = policy_scope(Dragon).geocoded
    end
    #@dragons = policy_scope(Dragon).geocoded
    @markers = @dragons.map do |dragon|
      {
        lat: dragon.latitude,
        lng: dragon.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { dragon: dragon }),
        image_url: helpers.asset_url('dragon-avatar-blackwhite.jpg')
      }
    end
  end

  def show
    @booking = Booking.new
    @diff = case @dragon.difficulty
    when 1
      "Easy"
    when 2
      "Medium"
    when 3
      "Hard"
    end
    @markers = [{
      lat: @dragon.latitude,
      lng: @dragon.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { dragon: @dragon }),
      image_url: helpers.asset_url('dragon-avatar-blackwhite.jpg')
    }]
  end

  def new
    @dragon = Dragon.new
    authorize @dragon
  end

  def create
    @dragon = Dragon.new(dragon_params)
    @dragon.user = current_user
    authorize @dragon

    if @dragon.save
      redirect_to dragon_path(@dragon)
    else
      render :new
    end
  end

  def edit; end

  def update
    @dragon.update(dragon_params)
    redirect_to dragon_path(@dragon)
  end

  def destroy
    @dragon.destroy
    redirect_to dragons_path
  end

  private

  def fetch_dragon
    @dragon = Dragon.find(params[:id])
    authorize @dragon
  end

  def dragon_params
    params.require(:dragon).permit(:name, :category, :age, :price_per_day, :difficulty, :address, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home

  end

  def my_dragons
    if params[:query].present?
      @dragons = Dragon.where(user:current_user).search_by_name_and_category(params[:query])
      authorize @dragons
    else
      @dragons = Dragon.where(user:current_user)
      authorize @dragons
    end
    @markers = @dragons.map do |dragon|
      {
        lat: dragon.latitude,
        lng: dragon.longitude,
        infoWindow: render_to_string(partial: "dragons/info_window", locals: { dragon: dragon }),
        image_url: helpers.asset_url('dragon-avatar-blackwhite.jpg')
      }
    end

    date = Date.today
    active_bookings = []
    Booking.all.each do |booking|
      if date >= booking.start_date && date <= booking.end_date
        active_bookings << booking
      end
    end

    @user_dragons_bookings = []
    active_bookings.each do |booking|
      if booking.dragon.user == current_user
        @user_dragons_bookings << booking
      end

    end
  end

  def my_bookings
    if params[:query].present?
      @bookings = Booking.where(user:current_user).search_by_dragon_name(params[:query])
    else
      @bookings = Booking.where(user:current_user)
    end
    authorize @bookings
    date = Date.today
    @active_bookings = []
    @bookings.each do |booking|
      if date >= booking.start_date && date <= booking.end_date
        @active_bookings << booking
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_calendar.html.erb
<%= month_calendar events: @dragon.bookings do |date, bookings| %>
  <%= date.day %>

  <% bookings.each do |booking| %>
  <% end %>
<% end %>

app/views/bookings/_list.html.erb
<% @dragon.bookings.each do |booking| %>
  <ul class="list-inline">
    <li><h3><strong><%= booking.user.first_name %> <%= booking.user.last_name %></strong></h3></li>
    <li><strong>Start date:</strong> <%= booking.start_date.strftime("%d %b %Y") %></li>
    <li><strong>End date:</strong>  <%= booking.end_date.strftime("%d %b %Y") %></li>
  </ul>
<% end %>

app/views/bookings/_new.html.erb
<h5 class="m-0 p-0">Add a new booking</h5>

<% if @booking.errors.any? %>
  <div class="alert alert-danger">
    <h3>Booking has errors!</h3>
    <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for [@dragon, @booking] do |f| %>
  <div class="m-0 p-0">
    <%= f.input :start_date, html5: true, class: 'form-control datepicker' %>
    <%= f.input :end_date, html5: true  %>
    <div class="edit-buttons">
      <button class="btn btn--border">
      <%= f.submit 'Create a booking'%>
      <span></span></button>
    </div>
  </div>

<% end %>

app/views/dragons/_form.html.erb
<!-- <div class="form-inputs">
  <%= f.input :name %>
  <div class="d-flex justify-content-between">
    <%= f.input :category %>
    <%= f.input :age %>
    <%= f.input :price_per_day, hint: 'please set price in euros €' %>
  </div>
  <%= f.input :difficulty %>
  <%= f.input :address %>
</div>
 -->

app/views/dragons/_info_window.html.erb
<div class ='info-window-content d-flex align-items-center justify-content-around'>
  <div class="photo">
  <% if dragon.photo.attached? %>
        <%= link_to dragon_path(dragon), class: 'info-window-img' do %>
          <%= cl_image_tag dragon.photo.key, width: 80, height: 80, crop: :fit, class:"info-window-img" %>
        <% end %>
    <% else %>
      <%= link_to dragon_path(dragon) do %>
        <img class = 'info-window-img' src="https://i.pinimg.com/originals/7d/d2/59/7dd259143b5aa431d457593ad991bc83.jpg" />
      <% end %>
    <% end %>
  </div>
  <div class ='info'>
    <h2 class = 'info-window-text'><%= dragon.name %></h2>
    <p class = 'info-window-text'><%= dragon.address %></p>
  </div>
</div>

app/views/dragons/_list.html.erb
<% @dragons.reverse_each do |dragon| %>
  <div class="card-dragon mt-3">
    <% if dragon.photo.attached? %>
        <%= link_to dragon_path(dragon) do %>
          <%= cl_image_tag dragon.photo.key, width: 180, height: 100, crop: :fit %>
        <% end %>
    <% else %>
      <%= link_to dragon_path(dragon) do %>
        <img src="https://i.pinimg.com/originals/7d/d2/59/7dd259143b5aa431d457593ad991bc83.jpg" />
      <% end %>
    <% end %>
    <div class="dragon-info">
      <% if dragon.user == current_user %>
      <div class="ribbon ribbon-top-right"><span>My Dragon</span></div>
      <% end %>
        <h2><%= link_to dragon.name, dragon_path(dragon) %></h2>
        <ul>
          <div>
            <li>Age: <%=dragon.age %> years</li>
            <div class="breeder-category">
              <li><i class="fas fa-magic"></i> <strong><%= dragon.user.first_name %> <%= dragon.user.last_name %></strong></li>
              <li><i class="fas fa-dragon"></i> <%=dragon.category %></li>
            </div>
            <div class="difficulty">
              <li>Difficulty: <% dragon.difficulty.times do %> <i class="fas fa-meteor"></i> <% end %> </li>
            </div>
          </div>
          <div class="the-price">
            <p> <%=dragon.price_per_day %></p>

            <div class="price-smaller">
              <p>€/day</p>
            </div>
          </div>
        </ul>
    </div>
  </div>


<% end %>

app/views/dragons/_map-show.html.erb
   <div
    class = 'map-show'
    id="map"
    style= " height: 100vh; position: sticky; top:50px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

app/views/dragons/_map.html.erb
   <div
    class = 'position-sticky w-100'
    id="map"
    style= " height: calc(100vh - 60px - 3rem); position: sticky; top: calc(60px + 1.5rem);"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

app/views/dragons/edit.html.erb
<div class="container-show col-8">

  <div class="card-show d-flex">
    <% if @dragon.photo.attached? %>
      <div class="card-show-image col-4 d-flex align-items-end p-3"
            style="background-image: url(<%= url_for(@dragon.photo) %>)">
    <% else %>
      <div class="card-show-image col-4 d-flex align-items-end p-3"
            style="background-image: linear-gradient(rgba(255, 255, 255, 0.7), rgba(255, 185, 52, 0.7)),
                                    url(https://i.pinimg.com/originals/5a/bb/cb/5abbcb44c878cb1d3c865892cf43c036.jpg)">
    <% end %>
      <%= simple_form_for @dragon do |f| %>
        <%= f.input :photo, as: :file %>
    </div>

    <div class="card-show-info col-8 p-3">
      <h2 class="form-title text-simple">Edit <%= @dragon.name %></h2>
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :category %>
        <div class="d-flex justify-content-between">
          <%= f.input :age %>

          <div class="d-flex flex-column is-valid">
            <label for="dragon_difficulty">Difficulty</label>
            <select class="custom-select mb-3 form-group" id="dragon_difficulty" name="dragon[difficulty]">
              <option value="1" selected>Easy</option>
              <option value="2">Medium</option>
              <option value="3">Hard</option>
            </select>
          </div>

          <%= f.input :price_per_day, hint: 'set price in euros €' %>
        </div>
        <%= f.input :address %>
      </div>
      <div class="edit-buttons">
      <div class="form-actions d-flex justify-content-between">
        <button class="btn btn--border">
        <%= f.button :submit, "Update dragon"%>
         <span></span></button>
        <div>
          <button class="btn btn--swap">
          <%= link_to "Delete Dragon", @dragon, data: { confirm: "Are you sure?" }, method: :delete %>
          <span>Are you sure?</span></button>
          <button class="btn btn--border">
          <%= link_to 'Cancel', @dragon %>
          <span></span></button>
        </div>
        <% end %>
      </div>
    </div>
    </div>
  </div>

</div>

app/views/dragons/index.html.erb
<div class="content-container d-flex justify-content-between">
    <div class="container-dragons col-8 pr-4">
      <%= render partial: 'list' %>
    </div>
    <div class = 'map-container col-4'>
      <%= render partial: 'map' %>
    </div>
</div>

app/views/dragons/new.html.erb
<div class="container-show col-8">

  <div class="card-show d-flex">
    <div class="card-show-image col-4 d-flex align-items-end p-3"
          style="background-image: linear-gradient(rgba(255, 255, 255, 0.7), rgba(255, 185, 52, 0.7)),
                                    url(https://i.pinimg.com/originals/5a/bb/cb/5abbcb44c878cb1d3c865892cf43c036.jpg)">
      <%= simple_form_for @dragon do |f| %>
        <%= f.input :photo, as: :file %>
    </div>

    <div class="card-show-info col-8 p-3">
      <h2 class="form-title text-simple">Add a Dragon</h2>
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :category %>
        <div class="d-flex justify-content-between">
          <%= f.input :age %>

          <div class="d-flex flex-column">
            <label for="dragon_difficulty">Difficulty</label>
            <select class="custom-select mb-3 form-group" id="dragon_difficulty" name="dragon[difficulty]">
              <option value="1" selected>Easy</option>
              <option value="2">Medium</option>
              <option value="3">Hard</option>
            </select>
          </div>

          <%= f.input :price_per_day, hint: 'set price in euros €' %>
        </div>
        <%= f.input :address %>
      </div>
      <div class="edit-buttons">
      <div class="form-actions d-flex justify-content-between">
         <button class="btn btn--border">
        <%= f.button :submit, "Add dragon" %>
        <span></span></button>
        <button class="btn btn--border">
        <%= link_to 'Cancel', dragons_path %>
        <span></span></button>
        <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/dragons/show.html.erb
<div class="container-show col-10">

  <div class="dragon d-flex p-0">
    <div class="dragon-image col-4 p-0">
      <% if @dragon.photo.attached? %>
        <%= cl_image_tag @dragon.photo.key, height: 600, width: 320, crop: :fill %>
      <% else %>
        <%= cl_image_tag 'nvou98k9mzayc2m57bm1', height: 600, width: 320, crop: :fill %>
      <% end %>
    </div>

    <div class="dragon-details col-8 m-0 px-3">

      <div class="dragon-card-info d-flex justify-content-between m-0">
        <div class="icons col-6 m-0 p-0">
          <h1><%= @dragon.name %></h1>
          <div class="d-flex justify-content-between pr-3">
            <div class="list-inline">
                <li><strong>Age:</strong> <%=@dragon.age %> years</li>
                <li><i class="fas fa-magic"></i> <%= @dragon.user.first_name %> <%= @dragon.user.last_name %></li>
                <li><i class="fas fa-dragon"></i> <%=@dragon.category %></li>
              <div class="difficulty">
                <li><strong>Difficulty:</strong> <% @dragon.difficulty.times do %> <i class="fas fa-meteor"></i> <% end %> </li>
              </div>
            </div>

            <div class="price text-center">
              <p class="m-0" style="font-size: 250%"><%=@dragon.price_per_day %></p>
              <p class="m-0">€ / day</p>
            </div>
          </div>
        </div>

        <div class="location-info col-6 p-0 mx-0 my-3">
          <%= render partial: 'dragons/map-show' %>
        </div>
      </div>

      <div class="edit-buttons d-flex justify-content-between">
        <% if policy(@dragon).edit? %>
        <button class="btn btn--border">
          <%= link_to 'Edit', edit_dragon_path(@dragon) %>
        <% end %>
        <span></span></button>

        <button class="btn btn--border">
        <%= link_to 'Back', dragons_path%>
         <span></span></button>

         <% if policy(@dragon).edit? %>
        <button class="btn btn--swap">
          <%= link_to 'Delete', @dragon, method: :delete, data: { confirm: "Are you sure?" } %>
        <span>Are you sure?</span></button>
        <% end %>
      </div>

      <div class="booking-details d-flex justify-content-between p-0 m-0 mt-4">
        <div class="booking-pick">
          <% if @dragon.user == current_user %>
            <%= render partial: 'bookings/list' %>
          <% elsif current_user %>
            <%= render partial: 'bookings/new' %>
          <% end %>
        </div>

        <div class="booking-calendar">
          <%= render partial: 'bookings/calendar' %>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dragons'Я'Us</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <div class="mega-container">

      <%= render 'shared/sidebar' %>

      <div class="main-container" style="margin-left: 240px;">

        <%= render 'shared/navbar' %>
        <% if action_name == 'home' %>
          <div class="yield-container">
            <%= yield %>
          </div>
        <% else %>
          <div class="yield-container p-4">
            <%= yield %>
          </div>
        <% end %>
      </div>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="main">
  <div class="hero">
    <!-- <h1>DRAGONS 'Я' US</h1> -->
    <!-- <br> -->
    <%= link_to dragons_path do %>
      <span style="font-family: 'Marcellus';" class="btn-fire slowly-grow">YOUR JOURNEY BEGINS HERE...</span>
    <% end %>
  </div>

  <div style="text-align: center;">
    <h2 class="mt-5 mb-3" style="color: white; font-family: 'Marcellus';">What we do</h2>
    <div class="cards-landing d-flex m-5">
      <div class="card-landing grow">
        <img src="http://dragonsworldguide.com/images/dragons/full/png256/mangrove-dragon.png" alt="Broken :(">
        <h3>Dragons</h3>
        <p>These AMAZING magical creatures are finally accessible at the distance of a click 🖱</p>
      </div>
      <div class="card-landing grow">
        <img src="http://dragonsworldguide.com/images/dragons/full/png256/blue-winged-dragon.png" alt="Broken :(">
        <h3>Fun</h3>
        <p>Have the trip of your life by renting and flying on the dragon of your dreams!</p>
      </div>
      <div class="card-landing grow">
        <img src="https://vignette.wikia.nocookie.net/dragons-world/images/3/34/MothDragonStore.png/revision/latest/scale-to-width-down/340?cb=20160808184047" alt="Broken :(">
        <h3>Bookings</h3>
        <p>Simple and fast system that allows you to book your favourite dragons for an emersive ride 🐉</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/my_bookings.html.erb
<div class="content-container d-flex justify-content-between">
  <div class="container-dragons col-8 pr-4 info-card-my-bookings">


    <% @bookings.each do |booking| %>
      <div class="info-card-my-dragons p-3">
        <h3><%= link_to booking.dragon.name, dragon_path(booking.dragon), class: 'link-my-dragons' %></h3>
        <div class="d-flex justify-content-between m-0">
          <div class="col-4 p-0 m-0">
            <p><strong>Start date:</strong> <br> <%= booking.start_date.strftime("%d %b %Y") %></p>
            <p><strong>End date:</strong> <br> <%= booking.end_date.strftime("%d %b %Y") %></p>
            <p class="m-0"><strong>Final price:</strong> <%= booking.total_price %> €</p>
          </div>
          <div class="col-6 p-0 m-0 text-center">

              <% if booking.countdown > 0 %>
                <h1><%= booking.countdown %></h1>
                <p>days until your booking</p>
              <% elsif booking.countdown == 0 %>
                <p><strong>You can get your dragon today!</strong></p>
              <% else %>
                <h1><%= booking.days_remaining %></h1>
                <div class="p-0 col-10">
                  <p>days remaining in your booking</p>
                </div>
              <% end %>

            <div class="edit-buttons">
              <% if policy(booking).destroy? %>
                <button class="btn btn--swap">
                  <%= link_to booking, method: :delete, data: { confirm: "Are you sure?" } do %>
                    Cancel Booking
                    <span>Are you sure?</span>
                  <% end %>
                </button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

  </div>
  <div class="my-dragons-side col-4 p-0">
    <div class="info-card-my-dragons p-3">
      <h4>Bookings Calendar</h4>
      <%= month_calendar events: @bookings do |date, bookings| %>
        <%= date.day %>

        <% bookings.each do |booking| %>
          <p><%= booking.dragon.name %></p>
        <% end %>
      <% end %>
    </div>
    <div class="info-card-my-dragons p-3 mt-3">
      <h2><strong><%= @active_bookings.count %></strong> dragons</h2>
      <p>are in your possession right now</p>
      <% @active_bookings.each do |booking| %>
        <hr>
        <h5><%= link_to booking.dragon.name, dragon_path(booking.dragon), class: 'link-my-dragons' %></h5>
        <div class="d-flex justify-content-between">
          <div class="col-4 p-0 m-0">
            <p><strong>Start date:</strong> <br> <%= booking.start_date.strftime("%d %b %Y") %></p>
            <p class="m-0"><strong>End date:</strong> <br> <%= booking.end_date.strftime("%d %b %Y") %></p>
          </div>
          <div class="d-flex flex-column justify-content-start align-items-center col-4 p-0 m-0">
            <h1><strong><%= booking.days_remaining %></strong></h1>
            <p>days left</p>
          </div>
          <% if booking.user.photo.attached? %>
            <div class="booking-user col-4 p-2 m-0 d-flex align-items-end"
                style="background-image: url(<%= url_for(booking.user.photo) %>)">
          <% else %>
            <div class="booking-user col-4 p-2 m-0 d-flex align-items-end"
                style="background-image: linear-gradient(rgba(255, 255, 255, 0.7), rgba(255, 185, 52, 0.7)),
                                          url(https://scontent.flis8-1.fna.fbcdn.net/v/t1.0-9/61093687_2196438233804291_364668622083194880_n.jpg?_nc_cat=110&_nc_ohc=_mSbFHftfskAX-4oKyU&_nc_ht=scontent.flis8-1.fna&oh=2f676f4defa17f0f99045e67ddd70659&oe=5EFD8E5A)">
          <% end %>

            <p class="m-0"><strong>Rider:</strong> <br>  <%= booking.user.first_name %> <%= booking.user.last_name %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidenav">
  <%= link_to root_path do %>
    <span style="font-family: 'Marcellus';">DRAGONS 'Я' US</span>
  <% end %>
  <hr>
  <div id="paths">
    <% if controller_name == 'dragons' && action_name == 'index' %>
      <%= link_to "Dragon's Lair", dragons_path, class: 'text-white mb-3' %>
    <% else %>
      <%= link_to "Dragon's Lair", dragons_path, class: 'mb-3' %>
    <% end %>

    <% if user_signed_in? %>
      <% if controller_name == 'dragons' && action_name == 'new' %>
        <%= link_to "Breed a dragon", new_dragon_path, class: 'text-white mt-5' %>
      <% else %>
        <%= link_to "Breed a dragon", new_dragon_path, class: 'mt-5' %>
      <% end %>
      <br>
      <% if controller_name == 'pages' && action_name == 'my_dragons' %>
        <%= link_to "My dragons", my_dragons_path, class: 'text-white mt-1' %>
      <% else %>
        <%= link_to "My dragons", my_dragons_path, class: 'mt-1' %>
      <% end %>
      <br>
      <% if controller_name == 'pages' && action_name == 'my_bookings' %>
        <%= link_to "My bookings", my_bookings_path, class: 'text-white mt-1' %>
      <% else %>
        <%= link_to "My bookings", my_bookings_path, class: 'mt-1' %>
      <% end %>
    <% end %>


  </div>
  <div class="footer">
    <div class="footer-links">
      <div class="d-flex">
        <a href="https://github.com/petah-sama/dragons-r-us" target="_blank"><i class="fab fa-github"></i></a>
        <a href="https://www.instagram.com/imaginedragons/?hl=en" target="_blank"><i class="fab fa-instagram"></i></a>
        <a href="https://www.facebook.com/DragonCity/" target="_blank"><i class="fab fa-facebook"></i></a>
      </div>
      <div class="d-flex center-footer">
        <a href="https://twitter.com/wizards_dnd?lang=en" target="_blank"><i class="fab fa-twitter"></i></a>
        <a href="https://www.linkedin.com/company/division7" target="_blank"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
  </div>
</div>